defaults: &node
  docker:
    - image: circleci/node:8

defaults: &docker
  docker:
    - image: quay.io/paulpop/docker-compose
      environment:
        APP_NAME: node-express-service
        IMAGE_NAME: quay.io/paulpop/node-express-service

version: 2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ~/node_modules
      - run:
          name: Check code formatting
          command: yarn lint
      - run:
          name: Run tests and upload to Codecov
          command: |
            yarn test
            bash <(curl -s https://codecov.io/bash)

  docker:
      <<: *docker
      steps:
        - checkout
        - setup_remote_docker
        - attach_workspace:
            at: .
        - run:
            name: Build container with the git commit sha version and latest version
            command: docker build -t andspuds/flight-info-api:$CIRCLE_SHA1 -t andspuds/flight-info-api .
        - run:
            name: Start container and verify it's healthy
            command: |
              set -x
              docker-compose up -d
              docker run --network container:$APP_NAME mwendler/wget -qO- \
                --retry-connrefused --tries=10 --waitretry 6 http://localhost:8080/health
        - run:
            name: Push image to Dockerhub
            command: |
              if [[ $CIRCLE_BRANCH == 'master' ]]; then
                  docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
                  docker push docker.io/andspuds/flight-info-api:$CIRCLE_SHA1
                  docker push docker.io/andspuds/flight-info-api
              else
                  echo Skipping this step as we are not on 'master' branch
              fi
        - run:
            name: Deploy latest image
            command: |
              ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-35-178-196-240.eu-west-2.compute.amazonaws.com -NL localhost:2374:/var/run/docker.sock docker@35.178.196.240 &
              docker service update --image andspuds/flight-info-api:$CIRCLE_SHA1 flight-info-api

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - docker:
          context: default
          requires:
            - build
